server:
  port: 8091
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${SHOP_DATASOURCE_URL:jdbc:postgresql://localhost:5441/shopDB}
    username: ${SHOP_DATASOURCE_USERNAME:postgres}
    password: ${SHOP_DATASOURCE_PASSWORD:shopservice}