server:
  port: 0
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${SHOP_DATASOURCE_URL:jdbc:postgresql://localhost:5441/shopDB}
    username: ${SHOP_DATASOURCE_USERNAME:postgres}
    password: ${SHOP_DATASOURCE_PASSWORD:shopservice}
  rabbitmq:
    username: ${SHOP_RABBITMQ_USERNAME:rmq_user}
    password: ${SHOP_RABBITMQ_PASSWORD:rmq_password}
    port: ${SHOP_RABBITMQ_PORT:5672}
  application:
    name: shop-service
rmq:
  event:
    product:
      queue: product.to.shop.event.queue
      exchange: product.event.exchange
      routing: routing.product.event.#
    shop:
      exchange: shop.event.exchange
      routing-prefix: routing.shop.event.
      routing-keys:
        shop_created: shop_created
        shop_product_link_created: shop_product_link_created
        shop_checked: shop_checked
        pickup_point_checked: pickup_point_checked
        order_product_checked: order_product_checked
        order_request_added: order_request_added
  command:
    queue: shop.command.queue
    exchange: shop.command.exchange
    routing: routing.shop.command.*
logging:
  pattern:
    console: "%clr(%d{ISO8601}){faint} %clr(%5p) %clr([%30.30t]){faint} %clr(%-40.40logger{36}.%M){cyan} %clr(:){faint} %m%n"
  level:
    org.hibernate: INFO
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_HOSTNAME:localhost}:${DISCOVERY_SERVICE_SERVER_PORT:8761}/eureka
  instance:
    prefer-ip-address: true
