server:
  port: 8091
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5441/shopDB
    username: m.surmach
    password: shopservice