version: '3.8'
services:
  user-service-db:
    image: postgres:14.2-alpine
    container_name: user-service-postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=userservice
      - POSTGRES_DB=usersDB
  shop-service-db:
    image: postgres:14.2-alpine
    container_name: shop-service-postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_PASSWORD=shopservice
      - POSTGRES_DB=shopDB
  product-service-db:
    image: postgres:14.2-alpine
    container_name: product-service-postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_PASSWORD=productservice
      - POSTGRES_DB=productDB
  order-service-db:
    image: postgres:14.2-alpine
    container_name: order-service-postgres
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_PASSWORD=orderservice
      - POSTGRES_DB=orderDB
  feedback-service-db:
    image: postgres:14.2-alpine
    container_name: feedback-service-postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=feedbackservice
      - POSTGRES_DB=feedbackDB
  rabbitmq:
    image: rabbitmq:3.10.25-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmq_user
      - RABBITMQ_DEFAULT_PASS=rmq_password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"