server:
  port: 8090
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${USERS_DATASOURCE_URL:jdbc:postgresql://localhost:5440/usersDB}
    username: ${USERS_DATASOURCE_URL:postgres}
    password: ${USERS_DATASOURCE_PASSWORD:userservice}