server:
  port: 8090
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5440/usersDB
    username: m.surmach
    password: userservice