server:
  port: 8090
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${USERS_DATASOURCE_URL:jdbc:postgresql://localhost:5440/usersDB}
    username: ${USERS_DATASOURCE_USERNAME:postgres}
    password: ${USERS_DATASOURCE_PASSWORD:userservice}
  rabbitmq:
    username: ${USERS_RABBITMQ_USERNAME:rmq_user}
    password: ${USERS_RABBITMQ_PASSWORD:rmq_password}
    port: ${USERS_RABBITMQ_PORT:5672}
rmq:
  event:
    user:
      exchange: user.event.exchange
      routing-prefix: routing.user.event.
      routing-keys:
        user_created: user_created
  command:
    queue: user.command.queue
    exchange: user.command.exchange
    routing: routing.user.command.*
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level [%thread] %logger{36}.%M - %msg%n"