server:
  port: 8093
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:postgresql://localhost:5443/orderDB}
    username: ${ORDER_DATASOURCE_USERNAME:postgres}
    password: ${ORDER_DATASOURCE_PASSWORD:orderservice}