server:
  port: 8092
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5442/productDB
    username: m.surmach
    password: productservice