server:
  port: 8092
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${PRODUCT_DATASOURCE_URL:jdbc:postgresql://localhost:5442/productDB}
    username: ${PRODUCT_DATASOURCE_USERNAME:postgres}
    password: ${PRODUCT_DATASOURCE_PASSWORD:productservice}
  rabbitmq:
    username: ${PRODUCT_RABBITMQ_USERNAME:rmq_user}
    password: ${PRODUCT_RABBITMQ_PASSWORD:rmq_password}
    port: ${PRODUCT_RABBITMQ_PORT:5672}
rmq:
  event:
    product:
      exchange: product.event.exchange
    shop:
      queue: shop.to.product.event.queue
      exchange: shop.event.exchange
      routing: routing.shop.event.#
  command:
    queue: product.command.queue
    exchange: product.command.exchange
    routing: routing.product.command.*