server:
  port: 8930
spring:
  main:
    banner-mode: off
#  liquibase:
#    change-log: db/changelog-master.xml
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:postgresql://localhost:5443/orderDB}
    username: ${ORDER_DATASOURCE_USERNAME:postgres}
    password: ${ORDER_DATASOURCE_PASSWORD:orderservice}
  rabbitmq:
    username: ${ORDER_RABBITMQ_USERNAME:rmq_user}
    password: ${ORDER_RABBITMQ_PASSWORD:rmq_password}
    port: ${ORDER_RABBITMQ_PORT:5672}
rmq:
  event:
    order:
      exchange: order.event.exchange
      routing-prefix: routing.order.event.
      routing-keys:
        order_initialized: order_initialized
  command:
    queue: order.command.queue
    exchange: order.command.exchange
    routing: routing.order.command.*
logging:
  pattern:
    console: "%clr(%d{ISO8601}){faint} %clr(%5p) %clr([%30.30t]){faint} %clr(%-40.40logger{36}.%M){cyan} %clr(:){faint} %m%n"