server:
  port: 8094
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${FEEDBACK_DATASOURCE_URL:jdbc:postgresql://localhost:5444/feedbackDB}
    username: ${FEEDBACK_DATASOURCE_USERNAME:postgres}
    password: ${FEEDBACK_DATASOURCE_PASSWORD:feedbackservice}
  rabbitmq:
    username: ${FEEDBACK_RABBITMQ_USERNAME:rmq_user}
    password: ${FEEDBACK_RABBITMQ_PASSWORD:rmq_password}
    port: ${FEEDBACK_RABBITMQ_PORT:5672}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        generate_statistics: true
rmq:
  event:
    feedback:
      exchange: feedback.event.exchange
    user:
      queue: user.to.feedback.event.queue
      exchange: user.event.exchange
      routing: routing.user.event.#
  command:
    queue: feedback.command.queue
    exchange: feedback.command.exchange
    routing: routing.feedback.command.*
logging:
  pattern:
    console: "%clr(%d{ISO8601}){faint} %clr(%5p) %clr([%30.30t]){faint} %clr(%-40.40logger{36}.%M){cyan} %clr(:){faint} %m%n"