server:
  port: 8094
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: ${FEEDBACK_DATASOURCE_URL:jdbc:postgresql://localhost:5444/feedbackDB}
    username: ${FEEDBACK_DATASOURCE_USERNAME:postgres}
    password: ${FEEDBACK_DATASOURCE_PASSWORD:feedbackservice}
  rabbitmq:
    username: ${FEEDBACK_RABBITMQ_USERNAME:rmq_user}
    password: ${FEEDBACK_RABBITMQ_PASSWORD:rmq_password}
    port: ${FEEDBACK_RABBITMQ_PORT:5672}
rmq:
  event:
    feedback:
      exchange: feedback.event.exchange
    user:
      queue: user.to.feedback.event.queue
      exchange: user.event.exchange
      routing: routing.user.event.#
  command:
    queue: feedback.command.queue
    exchange: feedback.command.exchange
    routing: routing.feedback.command.*